insert into ktms.countries (
    country_code,
    country_name,
    iso3_code,
    phone_code,
    currency_code,
    is_active,
    created_at,
    updated_at,
    created_channel_code,
    created_from_client,
    updated_channel_code,
    updated_from_client
)
values
    ('AD', '안도라', 'AND', '+376', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('AE', '아랍에미리트', 'ARE', '+971', 'AED', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('AF', '아프가니스탄', 'AFG', '+93', 'AFN', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('AG', '앤티가 바부다', 'ATG', '+1268', 'XCD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('AI', '앵귈라', 'AIA', '+1264', 'XCD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('AL', '알바니아', 'ALB', '+355', 'ALL', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('AM', '아르메니아', 'ARM', '+374', 'AMD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('AO', '앙골라', 'AGO', '+244', 'AOA', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('AQ', '남극', 'ATA', null, null, true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('AR', '아르헨티나', 'ARG', '+54', 'ARS', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('AS', '아메리칸사모아', 'ASM', '+1684', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('AT', '오스트리아', 'AUT', '+43', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('AU', '호주', 'AUS', '+61', 'AUD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('AW', '아루바', 'ABW', '+297', 'AWG', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('AX', '올란드 제도', 'ALA', '+35818', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('AZ', '아제르바이잔', 'AZE', '+994', 'AZN', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BA', '보스니아 헤르체고비나', 'BIH', '+387', 'BAM', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BB', '바베이도스', 'BRB', '+1246', 'BBD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BD', '방글라데시', 'BGD', '+880', 'BDT', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BE', '벨기에', 'BEL', '+32', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BF', '부르키나파소', 'BFA', '+226', 'XOF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BG', '불가리아', 'BGR', '+359', 'BGN', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BH', '바레인', 'BHR', '+973', 'BHD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BI', '부룬디', 'BDI', '+257', 'BIF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BJ', '베냉', 'BEN', '+229', 'XOF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BL', '생바르텔레미', 'BLM', '+590', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BM', '버뮤다', 'BMU', '+1441', 'BMD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BN', '브루나이', 'BRN', '+673', 'BND', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BO', '볼리비아', 'BOL', '+591', 'BOB', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BQ', '카리브 네덜란드', 'BES', '+599', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BR', '브라질', 'BRA', '+55', 'BRL', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BS', '바하마', 'BHS', '+1242', 'BSD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BT', '부탄', 'BTN', '+975', 'BTN', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BV', '부베 섬', 'BVT', '+47', null, true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BW', '보츠와나', 'BWA', '+267', 'BWP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BY', '벨라루스', 'BLR', '+375', 'BYN', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('BZ', '벨리즈', 'BLZ', '+501', 'BZD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CA', '캐나다', 'CAN', '+1', 'CAD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CC', '코코스 제도', 'CCK', '+61', 'AUD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CD', '콩고 민주 공화국', 'COD', '+243', 'CDF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CF', '중앙아프리카 공화국', 'CAF', '+236', 'XAF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CG', '콩고', 'COG', '+242', 'XAF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CH', '스위스', 'CHE', '+41', 'CHF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CI', '코트디부아르', 'CIV', '+225', 'XOF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CK', '쿡 제도', 'COK', '+682', 'CKD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CL', '칠레', 'CHL', '+56', 'CLP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CM', '카메룬', 'CMR', '+237', 'XAF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CN', '중국', 'CHN', '+86', 'CNY', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CO', '콜롬비아', 'COL', '+57', 'COP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CR', '코스타리카', 'CRI', '+506', 'CRC', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CU', '쿠바', 'CUB', '+53', 'CUC', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CV', '카보베르데', 'CPV', '+238', 'CVE', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CW', '퀴라소', 'CUW', '+599', 'ANG', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CX', '크리스마스 섬', 'CXR', '+61', 'AUD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CY', '키프로스', 'CYP', '+357', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('CZ', '체코', 'CZE', '+420', 'CZK', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('DE', '독일', 'DEU', '+49', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('DJ', '지부티', 'DJI', '+253', 'DJF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('DK', '덴마크', 'DNK', '+45', 'DKK', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('DM', '도미니카', 'DMA', '+1767', 'XCD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('DO', '도미니카 공화국', 'DOM', '+1809', 'DOP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('DZ', '알제리', 'DZA', '+213', 'DZD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('EC', '에콰도르', 'ECU', '+593', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('EE', '에스토니아', 'EST', '+372', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('EG', '이집트', 'EGY', '+20', 'EGP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('EH', '서사하라', 'ESH', '+212', 'DZD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('ER', '에리트레아', 'ERI', '+291', 'ERN', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('ES', '스페인', 'ESP', '+34', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('ET', '에티오피아', 'ETH', '+251', 'ETB', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('FI', '핀란드', 'FIN', '+358', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('FJ', '피지', 'FJI', '+679', 'FJD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('FK', '포클랜드 제도', 'FLK', '+500', 'FKP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('FM', '미크로네시아', 'FSM', '+691', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('FO', '페로 제도', 'FRO', '+298', 'DKK', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('FR', '프랑스', 'FRA', '+33', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GA', '가봉', 'GAB', '+241', 'XAF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GB', '영국', 'GBR', '+44', 'GBP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GD', '그레나다', 'GRD', '+1473', 'XCD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GE', '조지아', 'GEO', '+995', 'GEL', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GF', '프랑스령 기아나', 'GUF', '+594', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GG', '건지 섬', 'GGY', '+44', 'GBP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GH', '가나', 'GHA', '+233', 'GHS', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GI', '지브롤터', 'GIB', '+350', 'GIP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GL', '그린란드', 'GRL', '+299', 'DKK', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GM', '감비아', 'GMB', '+220', 'GMD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GN', '기니', 'GIN', '+224', 'GNF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GP', '과들루프', 'GLP', '+590', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GQ', '적도 기니', 'GNQ', '+240', 'XAF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GR', '그리스', 'GRC', '+30', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GS', '사우스조지아 사우스샌드위치 제도', 'SGS', '+500', 'GBP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GT', '과테말라', 'GTM', '+502', 'GTQ', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GU', '괌', 'GUM', '+1671', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GW', '기니비사우', 'GNB', '+245', 'XOF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('GY', '가이아나', 'GUY', '+592', 'GYD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('HK', '홍콩', 'HKG', '+852', 'HKD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('HM', '허드 맥도널드 제도', 'HMD', null, null, true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('HN', '온두라스', 'HND', '+504', 'HNL', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('HR', '크로아티아', 'HRV', '+385', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('HT', '아이티', 'HTI', '+509', 'HTG', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('HU', '헝가리', 'HUN', '+36', 'HUF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('ID', '인도네시아', 'IDN', '+62', 'IDR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('IE', '아일랜드', 'IRL', '+353', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('IL', '이스라엘', 'ISR', '+972', 'ILS', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('IM', '맨섬', 'IMN', '+44', 'GBP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('IN', '인도', 'IND', '+91', 'INR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('IO', '영국령 인도양 지역', 'IOT', '+246', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('IQ', '이라크', 'IRQ', '+964', 'IQD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('IR', '이란', 'IRN', '+98', 'IRR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('IS', '아이슬란드', 'ISL', '+354', 'ISK', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('IT', '이탈리아', 'ITA', '+39', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('JE', '저지 섬', 'JEY', '+44', 'GBP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('JM', '자메이카', 'JAM', '+1876', 'JMD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('JO', '요르단', 'JOR', '+962', 'JOD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('JP', '일본', 'JPN', '+81', 'JPY', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('KE', '케냐', 'KEN', '+254', 'KES', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('KG', '키르기스스탄', 'KGZ', '+996', 'KGS', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('KH', '캄보디아', 'KHM', '+855', 'KHR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('KI', '키리바시', 'KIR', '+686', 'AUD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('KM', '코모로', 'COM', '+269', 'KMF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('KN', '세인트키츠 네비스', 'KNA', '+1869', 'XCD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('KP', '조선', 'PRK', '+850', 'KPW', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('KR', '한국', 'KOR', '+82', 'KRW', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('KW', '쿠웨이트', 'KWT', '+965', 'KWD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('KY', '케이맨 제도', 'CYM', '+1345', 'KYD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('KZ', '카자흐스탄', 'KAZ', '+7', 'KZT', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('LA', '라오스', 'LAO', '+856', 'LAK', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('LB', '레바논', 'LBN', '+961', 'LBP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('LC', '세인트루시아', 'LCA', '+1758', 'XCD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('LI', '리히텐슈타인', 'LIE', '+423', 'CHF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('LK', '스리랑카', 'LKA', '+94', 'LKR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('LR', '라이베리아', 'LBR', '+231', 'LRD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('LS', '레소토', 'LSO', '+266', 'LSL', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('LT', '리투아니아', 'LTU', '+370', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('LU', '룩셈부르크', 'LUX', '+352', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('LV', '라트비아', 'LVA', '+371', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('LY', '리비아', 'LBY', '+218', 'LYD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MA', '모로코', 'MAR', '+212', 'MAD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MC', '모나코', 'MCO', '+377', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MD', '몰도바', 'MDA', '+373', 'MDL', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('ME', '몬테네그로', 'MNE', '+382', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MF', '생마르탱', 'MAF', '+590', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MG', '마다가스카르', 'MDG', '+261', 'MGA', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MH', '마셜 제도', 'MHL', '+692', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MK', '북마케도니아', 'MKD', '+389', 'MKD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('ML', '말리', 'MLI', '+223', 'XOF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MM', '미얀마', 'MMR', '+95', 'MMK', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MN', '몽골', 'MNG', '+976', 'MNT', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MO', '마카오', 'MAC', '+853', 'MOP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MP', '북마리아나 제도', 'MNP', '+1670', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MQ', '마르티니크', 'MTQ', '+596', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MR', '모리타니', 'MRT', '+222', 'MRU', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MS', '몬트세랫', 'MSR', '+1664', 'XCD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MT', '몰타', 'MLT', '+356', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MU', '모리셔스', 'MUS', '+230', 'MUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MV', '몰디브', 'MDV', '+960', 'MVR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MW', '말라위', 'MWI', '+265', 'MWK', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MX', '멕시코', 'MEX', '+52', 'MXN', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MY', '말레이시아', 'MYS', '+60', 'MYR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('MZ', '모잠비크', 'MOZ', '+258', 'MZN', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('NA', '나미비아', 'NAM', '+264', 'NAD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('NC', '누벨칼레도니', 'NCL', '+687', 'XPF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('NE', '니제르', 'NER', '+227', 'XOF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('NF', '노퍽 섬', 'NFK', '+672', 'AUD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('NG', '나이지리아', 'NGA', '+234', 'NGN', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('NI', '니카라과', 'NIC', '+505', 'NIO', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('NL', '네덜란드', 'NLD', '+31', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('NO', '노르웨이', 'NOR', '+47', 'NOK', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('NP', '네팔', 'NPL', '+977', 'NPR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('NR', '나우루', 'NRU', '+674', 'AUD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('NU', '니우에', 'NIU', '+683', 'NZD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('NZ', '뉴질랜드', 'NZL', '+64', 'NZD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('OM', '오만', 'OMN', '+968', 'OMR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('PA', '파나마', 'PAN', '+507', 'PAB', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('PE', '페루', 'PER', '+51', 'PEN', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('PF', '프랑스령 폴리네시아', 'PYF', '+689', 'XPF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('PG', '파푸아뉴기니', 'PNG', '+675', 'PGK', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('PH', '필리핀', 'PHL', '+63', 'PHP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('PK', '파키스탄', 'PAK', '+92', 'PKR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('PL', '폴란드', 'POL', '+48', 'PLN', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('PM', '생피에르 미클롱', 'SPM', '+508', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('PN', '핏케언 제도', 'PCN', '+64', 'NZD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('PR', '푸에르토리코', 'PRI', '+1787', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('PS', '팔레스타인', 'PSE', '+970', 'EGP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('PT', '포르투갈', 'PRT', '+351', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('PW', '팔라우', 'PLW', '+680', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('PY', '파라과이', 'PRY', '+595', 'PYG', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('QA', '카타르', 'QAT', '+974', 'QAR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('RE', '레위니옹', 'REU', '+262', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('RO', '루마니아', 'ROU', '+40', 'RON', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('RS', '세르비아', 'SRB', '+381', 'RSD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('RU', '러시아', 'RUS', '+7', 'RUB', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('RW', '르완다', 'RWA', '+250', 'RWF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SA', '사우디아라비아', 'SAU', '+966', 'SAR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SB', '솔로몬 제도', 'SLB', '+677', 'SBD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SC', '세이셸', 'SYC', '+248', 'SCR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SD', '수단', 'SDN', '+249', 'SDG', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SE', '스웨덴', 'SWE', '+46', 'SEK', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SG', '싱가포르', 'SGP', '+65', 'SGD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SH', '세인트헬레나', 'SHN', '+290', 'GBP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SI', '슬로베니아', 'SVN', '+386', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SJ', '스발바르 얀마옌 제도', 'SJM', '+4779', 'NOK', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SK', '슬로바키아', 'SVK', '+421', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SL', '시에라리온', 'SLE', '+232', 'SLE', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SM', '산마리노', 'SMR', '+378', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SN', '세네갈', 'SEN', '+221', 'XOF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SO', '소말리아', 'SOM', '+252', 'SOS', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SR', '수리남', 'SUR', '+597', 'SRD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SS', '남수단', 'SSD', '+211', 'SSP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('ST', '상투메 프린시페', 'STP', '+239', 'STN', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SV', '엘살바도르', 'SLV', '+503', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SX', '신트마르턴', 'SXM', '+1721', 'ANG', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SY', '시리아', 'SYR', '+963', 'SYP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('SZ', '에스와티니', 'SWZ', '+268', 'SZL', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('TC', '터크스 케이커스 제도', 'TCA', '+1649', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('TD', '차드', 'TCD', '+235', 'XAF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('TF', '프랑스령 남부와 남극 지역', 'ATF', '+262', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('TG', '토고', 'TGO', '+228', 'XOF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('TH', '태국', 'THA', '+66', 'THB', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('TJ', '타지키스탄', 'TJK', '+992', 'TJS', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('TK', '토켈라우', 'TKL', '+690', 'NZD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('TL', '동티모르', 'TLS', '+670', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('TM', '투르크메니스탄', 'TKM', '+993', 'TMT', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('TN', '튀니지', 'TUN', '+216', 'TND', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('TO', '통가', 'TON', '+676', 'TOP', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('TR', '터키', 'TUR', '+90', 'TRY', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('TT', '트리니다드 토바고', 'TTO', '+1868', 'TTD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('TV', '투발루', 'TUV', '+688', 'AUD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('TW', '대만', 'TWN', '+886', 'TWD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('TZ', '탄자니아', 'TZA', '+255', 'TZS', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('UA', '우크라이나', 'UKR', '+380', 'UAH', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('UG', '우간다', 'UGA', '+256', 'UGX', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('UM', '미국령 군소 제도', 'UMI', '+268', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('US', '미국', 'USA', '+1', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('UY', '우루과이', 'URY', '+598', 'UYU', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('UZ', '우즈베키스탄', 'UZB', '+998', 'UZS', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('VA', '바티칸', 'VAT', '+379', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('VC', '세인트빈센트 그레나딘', 'VCT', '+1784', 'XCD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('VE', '베네수엘라', 'VEN', '+58', 'VES', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('VG', '영국령 버진아일랜드', 'VGB', '+1284', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('VI', '미국령 버진아일랜드', 'VIR', '+1340', 'USD', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('VN', '베트남', 'VNM', '+84', 'VND', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('VU', '바누아투', 'VUT', '+678', 'VUV', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('WF', '왈리스 푸투나', 'WLF', '+681', 'XPF', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('WS', '사모아', 'WSM', '+685', 'WST', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('XK', '코소보', 'UNK', '+383', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('YE', '예멘', 'YEM', '+967', 'YER', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('YT', '마요트', 'MYT', '+262', 'EUR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('ZA', '남아프리카 공화국', 'ZAF', '+27', 'ZAR', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('ZM', '잠비아', 'ZMB', '+260', 'ZMW', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed'),
    ('ZW', '짐바브웨', 'ZWE', '+263', 'ZWL', true, now(), now(), 'SYSTEM', 'ktms-country-seed', 'SYSTEM', 'ktms-country-seed')
on conflict (country_code) do update set
    country_name = excluded.country_name,
    iso3_code = excluded.iso3_code,
    phone_code = excluded.phone_code,
    currency_code = excluded.currency_code,
    is_active = true,
    updated_at = now(),
    updated_channel_code = 'SYSTEM',
    updated_from_client = 'ktms-country-seed',
    deleted_at = null,
    deleted_by = null,
    deleted_channel_code = null,
    deleted_from_ip = null,
    deleted_from_location_id = null,
    deleted_from_client = null,
    deleted_reason = null;
