alter table ktms.tenants add column if not exists is_active boolean not null default true;
alter table ktms.companies add column if not exists is_active boolean not null default true;
alter table ktms.business_units add column if not exists is_active boolean not null default true;
alter table ktms.departments add column if not exists is_active boolean not null default true;
alter table ktms.app_users add column if not exists is_active boolean not null default true;
alter table ktms.business_partners add column if not exists is_active boolean not null default true;
alter table ktms.business_partner_roles add column if not exists is_active boolean not null default true;
alter table ktms.business_partner_relationships add column if not exists is_active boolean not null default true;
alter table ktms.partner_sites add column if not exists is_active boolean not null default true;
alter table ktms.partner_bank_accounts add column if not exists is_active boolean not null default true;
alter table ktms.carrier_profiles add column if not exists is_active boolean not null default true;
alter table ktms.carrier_lane_capacities add column if not exists is_active boolean not null default true;
alter table ktms.drivers add column if not exists is_active boolean not null default true;
alter table ktms.driver_certifications add column if not exists is_active boolean not null default true;
alter table ktms.vehicles add column if not exists is_active boolean not null default true;
alter table ktms.trailers add column if not exists is_active boolean not null default true;
alter table ktms.vehicle_documents add column if not exists is_active boolean not null default true;
alter table ktms.vehicle_maintenance add column if not exists is_active boolean not null default true;
alter table ktms.facilities add column if not exists is_active boolean not null default true;
alter table ktms.dock_doors add column if not exists is_active boolean not null default true;
alter table ktms.integration_channels add column if not exists is_active boolean not null default true;
alter table ktms.api_clients add column if not exists is_active boolean not null default true;
alter table ktms.api_client_permissions add column if not exists is_active boolean not null default true;
alter table ktms.permissions add column if not exists is_active boolean not null default true;
alter table ktms.role_permissions add column if not exists is_active boolean not null default true;
alter table ktms.user_roles add column if not exists is_active boolean not null default true;
alter table ktms.system_settings add column if not exists is_active boolean not null default true;
alter table ktms.client_locations add column if not exists is_active boolean not null default true;
alter table ktms.geo_zone_locations add column if not exists is_active boolean not null default true;
alter table ktms.operational_calendar_days add column if not exists is_active boolean not null default true;
alter table ktms.rate_agreements add column if not exists is_active boolean not null default true;
alter table ktms.rate_agreement_lanes add column if not exists is_active boolean not null default true;
alter table ktms.webhook_subscriptions add column if not exists is_active boolean not null default true;
alter table ktms.items add column if not exists is_active boolean not null default true;

update ktms.tenants set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.companies set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.business_units set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.departments set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.app_users set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.business_partners set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.business_partner_relationships set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.partner_sites set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.partner_bank_accounts set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.carrier_profiles set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.carrier_lane_capacities set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.drivers set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.driver_certifications set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED', 'EXPIRED', 'REVOKED');
update ktms.vehicles set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.trailers set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.vehicle_documents set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED', 'EXPIRED', 'REVOKED');
update ktms.vehicle_maintenance set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.facilities set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.dock_doors set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.integration_channels set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');
update ktms.api_clients set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED', 'REVOKED');
update ktms.rate_agreements set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED', 'EXPIRED');
update ktms.rate_agreement_lanes set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED', 'EXPIRED');
update ktms.webhook_subscriptions set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED', 'REVOKED');
update ktms.items set is_active = false where upper(status) in ('INACTIVE', 'DISABLED', 'SUSPENDED', 'BLOCKED', 'TERMINATED', 'CANCELLED');

comment on column ktms.tenants.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.companies.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.business_units.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.departments.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.app_users.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.business_partners.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.business_partner_roles.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.business_partner_relationships.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.partner_sites.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.partner_bank_accounts.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.carrier_profiles.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.carrier_lane_capacities.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.drivers.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.driver_certifications.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.vehicles.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.trailers.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.vehicle_documents.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.vehicle_maintenance.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.facilities.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.dock_doors.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.integration_channels.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.api_clients.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.api_client_permissions.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.permissions.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.role_permissions.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.user_roles.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.system_settings.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.client_locations.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.geo_zone_locations.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.operational_calendar_days.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.rate_agreements.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.rate_agreement_lanes.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.webhook_subscriptions.is_active is 'Whether this master record can be selected for new business use.';
comment on column ktms.items.is_active is 'Whether this master record can be selected for new business use.';
