// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGjJwtDX4QJVN9dwftvxT571ladNoEeDA',
    appId: '1:244152480982:web:1e089fa5ecbf61d44d8577',
    messagingSenderId: '244152480982',
    projectId: 'ktms-60214',
    authDomain: 'ktms-60214.firebaseapp.com',
    storageBucket: 'ktms-60214.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJsNTS9DUw1K53pg6u_6gQTcGt3PVB9Q4',
    appId: '1:244152480982:android:9649333eb4296bcb4d8577',
    messagingSenderId: '244152480982',
    projectId: 'ktms-60214',
    storageBucket: 'ktms-60214.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYeTK8HAjzNVCcm9sg35gg7jRB-nU8jpU',
    appId: '1:244152480982:ios:7d854616a78e0e3a4d8577',
    messagingSenderId: '244152480982',
    projectId: 'ktms-60214',
    storageBucket: 'ktms-60214.firebasestorage.app',
    iosClientId: '244152480982-l3iirma9hv3nrpr6bem3nv1khu1v8jl5.apps.googleusercontent.com',
    iosBundleId: 'com.kcastle.ktmsFrontend',
  );
}
